version: '3.3'

services:
  postgres:
    image: postgres:12.4
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_DATABASE}
    ports:
      - ${DATABASE_PORT}:5432
